spring.application.name=users-mvc

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3308/users-mvc}
spring.datasource.username=${DB_USERNAME:app}
spring.datasource.password=${DB_PASSWORD:app}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
